SELECT C.Z11_COD_PROCESO AS COD_PROCESO, C.Z11_NU_NUMERO_PROCESO, C.Z11_FE_FECHA_INICIO AS FEC_PROCESO   
FROM INFI_TB_Z11_PROCESOS C
WHERE C.Z10_CO_CODIGO_ARCHIVO = @cod_archivo@
ORDER BY C.Z11_COD_PROCESO ASC