SELECT B.Z02_OUT_CAMPO AS CAMPO_OUT, B.Z02_NUM_POSICION_SECUENCIA AS POSICION,B.Z02_IN_CAMPO_CONSTANTE AS CONSTANTE
FROM INFI_TB_Z00_MAPAS A, INFI_TB_Z02_CAMPOS_MAPA B
WHERE A.Z10_CO_CODIGO_ARCHIVO = @cod_archivo@
AND A.Z00_COD_MAPA = B.Z00_COD_MAPA
AND B.Z02_NUM_POSICION_SECUENCIA = @secuencia@
AND B.Z02_OUT_CAMPO IS NOT NULL
AND B.Z02_IN_CAMPO_CONSTANTE IS NOT NULL
AND B.Z02_IN_SEQUENCE IS NULL