SELECT D.Z01_CO_CODIGO_ENTIDAD AS COD_ENTIDAD, D.Z01_NO_NOMBRE_ENTIDAD AS NOM_ENTIDAD, D.Z01_NO_TABLA_ENTIDAD_1 AS ENTIDAD
FROM INFI_TB_Z01_ENTIDAD D, INFI_TB_Z10_ARCHIVOS A
WHERE A.Z10_CO_CODIGO_ARCHIVO = @cod_archivo@ 
AND D.Z01_CO_CODIGO_ENTIDAD = A.Z01_CO_CODIGO_ENTIDAD
ORDER BY D.Z01_CO_CODIGO_ENTIDAD ASC 