package com.bdv.infi.logic.interfaz_opics.message;

/**Representa el mensaje que debe enviarse a OPICS correspondiente a operación de cambio*/
public class MensajeOpicsOperacionCambio extends MensajeOpicsDetalle{

	//public final String BR="BR";
	//public final String SERVER="SERVER";
	//public final String FEDEALNO="FEDEALNO";
	//public final String SEQ="SEQ";
	//public final String INOUTIND="INOUTIND";
	public final String DEALNO="DEALNO";
	public final String NDEALNO="NDEALNO";
	public final String FDEALNO="FDEALNO";
	public final String TRAD="TRAD";
	public final String VDATE="VDATE";
	public final String NVDATE="NVDATE";
	public final String FVDATE="FVDATE";
	public final String CUST="CUST";
	public final String BROK="BROK";
	public final String BROKCCY="BROKCCY";
	public final String BROKAMT="BROKAMT";
	public final String PORT="PORT";
	public final String COST="COST";
	public final String ODATE="ODATE";
	public final String DEALDATE="DEALDATE";
	public final String DEALTEXT="DEALTEXT";
	public final String PS="PS";
	public final String CCY="CCY";
	public final String CCYAMT="CCYAMT";
	public final String CCYTERMS="CCYTERMS";
	public final String CCYRATE_8="CCYRATE_8";
	public final String CCYPD_8="CCYPD_8";
	public final String CTRCCY="CTRCCY";
	public final String CTRAMT="CTRAMT";
	public final String CCYBAMT="CCYBAMT";
	public final String BASETERMS="BASETERMS";
	public final String CCYBRATE_8="CCYBRATE_8";
	public final String CCYBPD_8="CCYBPD_8";
	public final String FCCYRATE_8="FCCYRATE_8";
	public final String FCCYPD_8="FCCYPD_8";
	public final String FCCYBAMT="FCCYBAMT";
	public final String FCCYBRATE_8="FCCYBRATE_8";
	public final String FCCYBPD_8="FCCYBPD_8";
	public final String NCCYRATE_8="NCCYRATE_8";
	public final String NCCYPD_8="NCCYPD_8";
	public final String NCCYBRATE_8="NCCYBRATE_8";
	public final String NCCYBPD_8="NCCYBPD_8";
	public final String NETSI="NETSI";
	public final String NNETSI="NNETSI";
	public final String FNETSI="FNETSI";
	public final String PHONECI="PHONECI";
	public final String LSTMNTDATE="LSTMNTDATE";
	public final String SIIND="SIIND";
	public final String VERIND="VERIND";
	public final String CCYSMEANS="CCYSMEANS";
	public final String CCYSACCT="CCYSACCT";
	public final String CTRSMEANS="CTRSMEANS";
	public final String CTRSACCT="CTRSACCT";
	public final String SUPPAYIND="SUPPAYIND";
	public final String SUPRECIND="SUPRECIND";
	public final String SUPCONFIND="SUPCONFIND";
	public final String SUPPLEMENTAL="SUPPLEMENTAL";
	public final String SUPPCANCELIND="SUPPCANCELIND";
	public final String PRODCODE="PRODCODE";
	public final String PRODTYPE="PRODTYPE";
	public final String REVTEXT="REVTEXT";
	public final String REVREASON="REVREASON";
	public final String COMMCCY="COMMCCY";
	public final String COMMAMT="COMMAMT";
	public final String SPOTTRAD="SPOTTRAD";
	public final String SPOTPORT="SPOTPORT";
	public final String SPOTCOST="SPOTCOST";
	public final String CORPTRAD="CORPTRAD";
	public final String CORPPORT="CORPPORT";
	public final String CORPCOST="CORPCOST";
	public final String CORPCCY="CORPCCY";
	public final String CORPSPREAD_8="CORPSPREAD_8";
	public final String INTERNALRATE_8="INTERNALRATE_8";
	public final String BRSPREAD_8="BRSPREAD_8";
	public final String BRCOST="BRCOST";
	public final String SPOTCCY="SPOTCCY";
	public final String CORPSPREADAMT="CORPSPREADAMT";
	public final String FIXRATEIND="FIXRATEIND";
	public final String FIXRATECODE="FIXRATECODE";
	public final String BLOCKIND="BLOCKIND";
	public final String DISAGGCCY="DISAGGCCY";
	public final String DISAGGSPOTTRAD="DISAGGSPOTTRAD";
	public final String DISAGGSPOTPORT="DISAGGSPOTPORT";
	public final String DISAGGSPOTCOST="DISAGGSPOTCOST";
	public final String DISAGGFWDTRAD="DISAGGFWDTRAD";
	public final String DISAGGFWDPORT="DISAGGFWDPORT";
	public final String DISAGGFWDCOST="DISAGGFWDCOST";
	public final String TENOR="TENOR";
	public final String NTENOR="NTENOR";
	public final String FTENOR="FTENOR";
	public final String NPRODCODE="NPRODCODE";
	public final String FPRODCODE="FPRODCODE";
	public final String NPRODTYPE="NPRODTYPE";
	public final String FPRODTYPE="FPRODTYPE";
	public final String NCUST="NCUST";
	public final String FCUST="FCUST";
	public final String NOTETEXT="NOTETEXT";
	public final String CCYUSUALID="CCYUSUALID";
	public final String CTRUSUALID="CTRUSUALID";
	public final String CUSTREFNO="CUSTREFNO";
	public final String CCYTYPECODE="CCYTYPECODE";
	public final String CTRTYPECODE="CTRTYPECODE";
	public final String CTRSETTDATE="CTRSETTDATE";
	public final String NCTRSETTDATE="NCTRSETTDATE";
	public final String FCTRSETTDATE="FCTRSETTDATE";
	public final String AUTHSI="AUTHSI";
	public final String MANUALSETTLE="MANUALSETTLE";
	public final String DELETEINSTR="DELETEINSTR";
	public final String INTERBRANCHIND="INTERBRANCHIND";
	public final String INTERBRANCHNO="INTERBRANCHNO";
	public final String FCCYAMT="FCCYAMT";
	public final String DEALTIME="DEALTIME";
	public final String MATCHIND="MATCHIND";
	public final String FCCYUSUALID="FCCYUSUALID";
	public final String FCTRUSUALID="FCTRUSUALID";
	public final String FCCYTYPECODE="FCCYTYPECODE";
	public final String FCTRTYPECODE="FCTRTYPECODE";
	public final String FCCYSMEANS="FCCYSMEANS";
	public final String FCCYSACCT="FCCYSACCT";
	public final String FCTRSMEANS="FCTRSMEANS";
	public final String FCTRSACCT="FCTRSACCT";
	public final String HEDGEIND="HEDGEIND";
	public final String NDFIND="NDFIND";
	public final String TDSPLIND="TDSPLIND";
	public final String TDSPLCUST="TDSPLCUST";
	public final String TDVDATE="TDVDATE";
	public final String ORIGNDFDEALNO="ORIGNDFDEALNO";
	public final String ZERORATEIND="ZERORATEIND";
	public final String NCTRAMT="NCTRAMT";
	public final String FCTRAMT="FCTRAMT";
	public final String DATE1="DATE1";
	public final String DATE2="DATE2";
	public final String RATE1_8="RATE1_8";
	public final String RATE2_8="RATE2_8";
	public final String AMT1="AMT1";
	public final String AMT2="AMT2";
	public final String TEXT1="TEXT1";
	public final String TEXT2="TEXT2";
	public final String NCORPSPREAD_8="NCORPSPREAD_8";
	public final String NINTERNALRATE_8="NINTERNALRATE_8";
	public final String NCORPSPREADAMT="NCORPSPREADAMT";
	public final String FCORPSPREAD_8="FCORPSPREAD_8";
	public final String FINTERNALRATE_8="FINTERNALRATE_8";
	public final String FCORPSPREADAMT="FCORPSPREADAMT";
	public final String BACKTOBACKSWAPIND="BACKTOBACKSWAPIND";
	public final String CCYINTERESTRATE_8="CCYINTERESTRATE_8";
	public final String CTRINTERESTRATE_8="CTRINTERESTRATE_8";
	public final String CCYLINKDEALNO="CCYLINKDEALNO";
	public final String CTRLINKDEALNO="CTRLINKDEALNO";
	public final String CCYTODISAGGRATE_8="CCYTODISAGGRATE_8";
	public final String CCYTODISAGGPD_8="CCYTODISAGGPD_8";
	public final String CCYTODISAGGSPREAD_8="CCYTODISAGGSPREAD_8";
	public final String CCYTODISAGGTERMS="CCYTODISAGGTERMS";
	public final String NCCYTODISAGGRATE_8="NCCYTODISAGGRATE_8";
	public final String NCCYTODISAGGPD_8="NCCYTODISAGGPD_8";
	public final String NCCYTODISAGGSPREAD_8="NCCYTODISAGGSPREAD_8";
	public final String NCCYTODISAGGTERMS="NCCYTODISAGGTERMS";
	public final String FCCYTODISAGGRATE_8="FCCYTODISAGGRATE_8";
	public final String FCCYTODISAGGPD_8="FCCYTODISAGGPD_8";
	public final String FCCYTODISAGGSPREAD_8="FCCYTODISAGGSPREAD_8";
	public final String FCCYTODISAGGTERMS="FCCYTODISAGGTERMS";
	public final String MARGINFEEAMT="MARGINFEEAMT";
	public final String MARGINREBATEAMT="MARGINREBATEAMT";
	public final String NMARGINFEEAMT="NMARGINFEEAMT";
	public final String NMARGINREBATEAMT="NMARGINREBATEAMT";
	public final String FMARGINFEEAMT="FMARGINFEEAMT";
	public final String FMARGINREBATEAMT="FMARGINREBATEAMT";

	
	/**Constructor que inicializa las variables*/
	public MensajeOpicsOperacionCambio(){
		//valores.put(BR, this.VALOR_VACIO);
		//valores.put(SERVER, this.VALOR_VACIO);
		//valores.put(FEDEALNO, this.VALOR_VACIO);
		//valores.put(SEQ, this.VALOR_VACIO);
		//valores.put(INOUTIND, this.VALOR_VACIO);
		valores.put(DEALNO, this.VALOR_VACIO);
		valores.put(NDEALNO, this.VALOR_VACIO);
		valores.put(FDEALNO, this.VALOR_VACIO);
		valores.put(TRAD, this.VALOR_VACIO);
		valores.put(VDATE, this.VALOR_VACIO);
		valores.put(NVDATE, this.VALOR_VACIO);
		valores.put(FVDATE, this.VALOR_VACIO);
		valores.put(CUST, this.VALOR_VACIO);
		valores.put(BROK, this.VALOR_VACIO);
		valores.put(BROKCCY, this.VALOR_VACIO);
		valores.put(BROKAMT, this.VALOR_VACIO);
		valores.put(PORT, this.VALOR_VACIO);
		valores.put(COST, this.VALOR_VACIO);
		valores.put(ODATE, this.VALOR_VACIO);
		valores.put(DEALDATE, this.VALOR_VACIO);
		valores.put(DEALTEXT, this.VALOR_VACIO);
		valores.put(PS, this.VALOR_VACIO);
		valores.put(CCY, this.VALOR_VACIO);
		valores.put(CCYAMT, this.VALOR_VACIO);
		valores.put(CCYTERMS, this.VALOR_VACIO);
		valores.put(CCYRATE_8, this.VALOR_VACIO);
		valores.put(CCYPD_8, this.VALOR_VACIO);
		valores.put(CTRCCY, this.VALOR_VACIO);
		valores.put(CTRAMT, this.VALOR_VACIO);
		valores.put(CCYBAMT, this.VALOR_VACIO);
		valores.put(BASETERMS, this.VALOR_VACIO);
		valores.put(CCYBRATE_8, this.VALOR_VACIO);
		valores.put(CCYBPD_8, this.VALOR_VACIO);
		valores.put(FCCYRATE_8, this.VALOR_VACIO);
		valores.put(FCCYPD_8, this.VALOR_VACIO);
		valores.put(FCCYBAMT, this.VALOR_VACIO);
		valores.put(FCCYBRATE_8, this.VALOR_VACIO);
		valores.put(FCCYBPD_8, this.VALOR_VACIO);
		valores.put(NCCYRATE_8, this.VALOR_VACIO);
		valores.put(NCCYPD_8, this.VALOR_VACIO);
		valores.put(NCCYBRATE_8, this.VALOR_VACIO);
		valores.put(NCCYBPD_8, this.VALOR_VACIO);
		valores.put(NETSI, this.VALOR_VACIO);
		valores.put(NNETSI, this.VALOR_VACIO);
		valores.put(FNETSI, this.VALOR_VACIO);
		valores.put(PHONECI, this.VALOR_VACIO);
		valores.put(LSTMNTDATE, this.VALOR_VACIO);
		valores.put(SIIND, this.VALOR_VACIO);
		valores.put(VERIND, this.VALOR_VACIO);
		valores.put(CCYSMEANS, this.VALOR_VACIO);
		valores.put(CCYSACCT, this.VALOR_VACIO);
		valores.put(CTRSMEANS, this.VALOR_VACIO);
		valores.put(CTRSACCT, this.VALOR_VACIO);
		valores.put(SUPPAYIND, this.VALOR_VACIO);
		valores.put(SUPRECIND, this.VALOR_VACIO);
		valores.put(SUPCONFIND, this.VALOR_VACIO);
		valores.put(SUPPLEMENTAL, this.VALOR_VACIO);
		valores.put(SUPPCANCELIND, this.VALOR_VACIO);
		valores.put(PRODCODE, this.VALOR_VACIO);
		valores.put(PRODTYPE, this.VALOR_VACIO);
		valores.put(REVTEXT, this.VALOR_VACIO);
		valores.put(REVREASON, this.VALOR_VACIO);
		valores.put(COMMCCY, this.VALOR_VACIO);
		valores.put(COMMAMT, this.VALOR_VACIO);
		valores.put(SPOTTRAD, this.VALOR_VACIO);
		valores.put(SPOTPORT, this.VALOR_VACIO);
		valores.put(SPOTCOST, this.VALOR_VACIO);
		valores.put(CORPTRAD, this.VALOR_VACIO);
		valores.put(CORPPORT, this.VALOR_VACIO);
		valores.put(CORPCOST, this.VALOR_VACIO);
		valores.put(CORPCCY, this.VALOR_VACIO);
		valores.put(CORPSPREAD_8, this.VALOR_VACIO);
		valores.put(INTERNALRATE_8, this.VALOR_VACIO);
		valores.put(BRSPREAD_8, this.VALOR_VACIO);
		valores.put(BRCOST, this.VALOR_VACIO);
		valores.put(SPOTCCY, this.VALOR_VACIO);
		valores.put(CORPSPREADAMT, this.VALOR_VACIO);
		valores.put(FIXRATEIND, this.VALOR_VACIO);
		valores.put(FIXRATECODE, this.VALOR_VACIO);
		valores.put(BLOCKIND, this.VALOR_VACIO);
		valores.put(DISAGGCCY, this.VALOR_VACIO);
		valores.put(DISAGGSPOTTRAD, this.VALOR_VACIO);
		valores.put(DISAGGSPOTPORT, this.VALOR_VACIO);
		valores.put(DISAGGSPOTCOST, this.VALOR_VACIO);
		valores.put(DISAGGFWDTRAD, this.VALOR_VACIO);
		valores.put(DISAGGFWDPORT, this.VALOR_VACIO);
		valores.put(DISAGGFWDCOST, this.VALOR_VACIO);
		valores.put(TENOR, this.VALOR_VACIO);
		valores.put(NTENOR, this.VALOR_VACIO);
		valores.put(FTENOR, this.VALOR_VACIO);
		valores.put(NPRODCODE, this.VALOR_VACIO);
		valores.put(FPRODCODE, this.VALOR_VACIO);
		valores.put(NPRODTYPE, this.VALOR_VACIO);
		valores.put(FPRODTYPE, this.VALOR_VACIO);
		valores.put(NCUST, this.VALOR_VACIO);
		valores.put(FCUST, this.VALOR_VACIO);
		valores.put(NOTETEXT, this.VALOR_VACIO);
		valores.put(CCYUSUALID, this.VALOR_VACIO);
		valores.put(CTRUSUALID, this.VALOR_VACIO);
		valores.put(CUSTREFNO, this.VALOR_VACIO);
		valores.put(CCYTYPECODE, this.VALOR_VACIO);
		valores.put(CTRTYPECODE, this.VALOR_VACIO);
		valores.put(CTRSETTDATE, this.VALOR_VACIO);
		valores.put(NCTRSETTDATE, this.VALOR_VACIO);
		valores.put(FCTRSETTDATE, this.VALOR_VACIO);
		valores.put(AUTHSI, this.VALOR_VACIO);
		valores.put(MANUALSETTLE, this.VALOR_VACIO);
		valores.put(DELETEINSTR, this.VALOR_VACIO);
		valores.put(INTERBRANCHIND, this.VALOR_VACIO);
		valores.put(INTERBRANCHNO, this.VALOR_VACIO);
		valores.put(FCCYAMT, this.VALOR_VACIO);
		valores.put(DEALTIME, this.VALOR_VACIO);
		valores.put(MATCHIND, this.VALOR_VACIO);
		valores.put(FCCYUSUALID, this.VALOR_VACIO);
		valores.put(FCTRUSUALID, this.VALOR_VACIO);
		valores.put(FCCYTYPECODE, this.VALOR_VACIO);
		valores.put(FCTRTYPECODE, this.VALOR_VACIO);
		valores.put(FCCYSMEANS, this.VALOR_VACIO);
		valores.put(FCCYSACCT, this.VALOR_VACIO);
		valores.put(FCTRSMEANS, this.VALOR_VACIO);
		valores.put(FCTRSACCT, this.VALOR_VACIO);
		valores.put(HEDGEIND, this.VALOR_VACIO);
		valores.put(NDFIND, this.VALOR_VACIO);
		valores.put(TDSPLIND, this.VALOR_VACIO);
		valores.put(TDSPLCUST, this.VALOR_VACIO);
		valores.put(TDVDATE, this.VALOR_VACIO);
		valores.put(ORIGNDFDEALNO, this.VALOR_VACIO);
		valores.put(ZERORATEIND, this.VALOR_VACIO);
		valores.put(NCTRAMT, this.VALOR_VACIO);
		valores.put(FCTRAMT, this.VALOR_VACIO);
		valores.put(DATE1, this.VALOR_VACIO);
		valores.put(DATE2, this.VALOR_VACIO);
		valores.put(RATE1_8, this.VALOR_VACIO);
		valores.put(RATE2_8, this.VALOR_VACIO);
		valores.put(AMT1, this.VALOR_VACIO);
		valores.put(AMT2, this.VALOR_VACIO);
		valores.put(TEXT1, this.VALOR_VACIO);
		valores.put(TEXT2, this.VALOR_VACIO);
		valores.put(NCORPSPREAD_8, this.VALOR_VACIO);
		valores.put(NINTERNALRATE_8, this.VALOR_VACIO);
		valores.put(NCORPSPREADAMT, this.VALOR_VACIO);
		valores.put(FCORPSPREAD_8, this.VALOR_VACIO);
		valores.put(FINTERNALRATE_8, this.VALOR_VACIO);
		valores.put(FCORPSPREADAMT, this.VALOR_VACIO);
		valores.put(BACKTOBACKSWAPIND, this.VALOR_VACIO);
		valores.put(CCYINTERESTRATE_8, this.VALOR_VACIO);
		valores.put(CTRINTERESTRATE_8, this.VALOR_VACIO);
		valores.put(CCYLINKDEALNO, this.VALOR_VACIO);
		valores.put(CTRLINKDEALNO, this.VALOR_VACIO);
		valores.put(CCYTODISAGGRATE_8, this.VALOR_VACIO);
		valores.put(CCYTODISAGGPD_8, this.VALOR_VACIO);
		valores.put(CCYTODISAGGSPREAD_8, this.VALOR_VACIO);
		valores.put(CCYTODISAGGTERMS, this.VALOR_VACIO);
		valores.put(NCCYTODISAGGRATE_8, this.VALOR_VACIO);
		valores.put(NCCYTODISAGGPD_8, this.VALOR_VACIO);
		valores.put(NCCYTODISAGGSPREAD_8, this.VALOR_VACIO);
		valores.put(NCCYTODISAGGTERMS, this.VALOR_VACIO);
		valores.put(FCCYTODISAGGRATE_8, this.VALOR_VACIO);
		valores.put(FCCYTODISAGGPD_8, this.VALOR_VACIO);
		valores.put(FCCYTODISAGGSPREAD_8, this.VALOR_VACIO);
		valores.put(FCCYTODISAGGTERMS, this.VALOR_VACIO);
		valores.put(MARGINFEEAMT, this.VALOR_VACIO);
		valores.put(MARGINREBATEAMT, this.VALOR_VACIO);
		valores.put(NMARGINFEEAMT, this.VALOR_VACIO);
		valores.put(NMARGINREBATEAMT, this.VALOR_VACIO);
		valores.put(FMARGINFEEAMT, this.VALOR_VACIO);
		valores.put(FMARGINREBATEAMT, this.VALOR_VACIO);
		
		valores.put(this.TIPO_MENSAJE, this.OPERACION_CAMBIO);
		valores.put(this.BRANCH, this.BRANCHDEFECTO);
		valores.put(this.ORDENEID, this.VALOR_VACIO);
	}
}
