package com.bdv.infi.logic.interfaz_opics.message;

/**Representa el mensaje que debe enviarse a OPICS correspondiente a renta fija*/
public class MensajeOpicsRentaFija extends MensajeOpicsDetalle{
		
	public final String DEALNO = "DEALNO";
	public final String CNO = "CNO";
	public final String SECSACCT = "SECSACCT";
	public final String PS  = "PS";
	public final String INVTYPE = "INVTYPE";
	public final String ORIGAMT = "ORIGAMT";
	public final String PORT = "PORT";
	public final String TRAD = "TRAD";
	public final String SECID = "SECID";
	public final String DISCRATE_8 = "DISCRATE_8";
	public final String ORIGQTY = "ORIGQTY";
	public final String PRICE_8  = "PRICE_8";
	public final String SETTDATE = "SETTDATE";
	public final String COMMAMT = "COMMAMT";
	public final String FEEAMT = "FEEAMT";
	public final String VATAMT = "VATAMT";
	public final String BROKFEEAMT = "BROKFEEAMT";
	public final String BROK = "BROK";
	public final String YIELD_8 = "YIELD_8";
	public final String SPREADRATE_8 = "SPREADRATE_8";
	public final String COST = "COST";
	public final String RATECODE = "RATECODE";
	public final String DELAYDELVIND = "DELAYDELVIND";
	public final String DEALDATE  = "DEALDATE";
	public final String DEALTIME  = "DEALTIME";
	public final String DEALTEXT = "DEALTEXT";
	public final String EXCHIND = "EXCHIND";
	public final String VERIND = "VERIND";
	public final String VERDATE = "VERDATE";
	public final String STANDINSTR = "STANDINSTR";
	public final String REVREASON = "REVREASON";
	public final String REVTEXT = "REVTEXT";
	public final String CONVINTAMT = "CONVINTAMT";
	public final String CONVINTBAMT = "CONVINTBAMT";
	public final String SETTAMT = "SETTAMT";
	public final String SETTBASEAMT = "SETTBASEAMT";
	public final String COSTAMT = "COSTAMT";
	public final String COSTBAMT = "COSTBAMT";
	public final String WHTAMT = "WHTAMT";
	public final String INTCCY = "INTCCY";
	public final String SETTCCY = "SETTCCY";
	public final String SETTPROCEXCHRATE_8 = "SETTPROCEXCHRATE_8";
	public final String SETTPROCTERMS = "SETTPROCTERMS";
	public final String SETTPROCPREMDISC_8 = "SETTPROCPREMDISC_8";
	public final String INTSETTEXCHRATE_8 = "INTSETTEXCHRATE_8";
	public final String INTSETTTERMS = "INTSETTTERMS";
	public final String INTSETTPREMDISC_8 = "INTSETTPREMDISC_8";
	public final String SETTBASEEXCHRATE_8 = "SETTBASEEXCHRATE_8";
	public final String SETTBASETERMS  = "SETTBASETERMS";
	public final String SETTBASEPREMDISC_8 = "SETTBASEPREMDISC_";
	public final String INTBASEEXCHRATE_8  = "INTBASEEXCHRATE_8";
	public final String INTBASETERMS  = "INTBASETERMS";
	public final String INTBASEPREMDISC_8  = "INTBASEPREMDISC_8";
	public final String CCYSMEANS  = "CCYSMEANS";
	public final String CCYSACCT = "CCYSACCT";
	public final String BENBIC = "BENBIC";
	public final String BEN1 = "BEN1";
	public final String BEN2 = "BEN2";
	public final String BEN3 = "BEN3";
	public final String BEN4 = "BEN4";
	public final String RECDELBIC  = "RECDELBIC";
	public final String RECDEL1  = "RECDEL1";
	public final String RECDEL2  = "RECDEL2";
	public final String RECDEL3  = "RECDEL3";
	public final String RECDEL4  = "RECDEL4";
	public final String COLLATERALID  ="COLLATERALID";
	public final String OVERRIDEWXTAXIND  ="OVERRIDEWXTAXIND";
	public final String LINKFEDEALNO  ="LINKFEDEALNO";
	public final String LINKFESEQ  ="LINKFESEQ";
	public final String EOPICSIND  ="EOPICSIND";
	public final String INTERNALYIELD_8 ="INTERNALYIELD_8";
	public final String INTERNALDISCRATE_8 ="INTERNALDISCRATE_8";
	public final String INTERNALPRICE_8  ="INTERNALPRICE_8";
	public final String INTERNALPROCEEDAMT  ="INTERNALPROCEEDAMT";
	public final String INTERNALSPREADRATE_8 ="INTERNALSPREADRATE_8";
	public final String MARKUPCOMMAMT  ="MARKUPCOMMAMT";
	public final String AMORTYIELD_8  ="AMORTYIELD_8";
	public final String AMORTIND  ="AMORTIND";
	public final String PLEDGEID  ="PLEDGEID";
	public final String PRODUCT  ="PRODUCT";
	public final String PRODTYPE  ="PRODTYPE";
	public final String ISSUER  ="ISSUER";
	public final String CRATING  ="CRATING";
	public final String RATCNO  ="RATCNO";
	public final String FROMDAYS  ="FROMDAYS";
	public final String TODAYS  ="TODAYS";
	public final String ASSIGNSEQ  ="ASSIGNSEQ";
	public final String RECOURSEIND  ="RECOURSEIND";
	public final String USUALID  ="USUALID";
	public final String SUPPCONFIND  ="SUPPCONFIND";
	public final String SUPPSEC  ="SUPPSEC";
	public final String SUPPCCY  ="SUPPCCY";
	
	/**Constructor que inicializa las variables*/
	@SuppressWarnings("static-access")
	public MensajeOpicsRentaFija(){
		
		valores.put(DEALNO, this.VALOR_VACIO);
		valores.put(CNO, this.VALOR_VACIO);
		valores.put(SECSACCT, this.VALOR_VACIO);
		valores.put(PS , this.VALOR_VACIO);
		valores.put(INVTYPE, this.VALOR_VACIO);
		valores.put(ORIGAMT, this.VALOR_VACIO);
		valores.put(PORT, this.VALOR_VACIO);
		valores.put(TRAD, this.VALOR_VACIO);
		valores.put(SECID, this.VALOR_VACIO);
		valores.put(DISCRATE_8, this.VALOR_VACIO);
		valores.put(ORIGQTY, this.VALOR_VACIO);
		valores.put(PRICE_8 , this.VALOR_VACIO);
		valores.put(SETTDATE, this.VALOR_VACIO);
		valores.put(COMMAMT, this.VALOR_VACIO);
		valores.put(FEEAMT, this.VALOR_VACIO);
		valores.put(VATAMT, this.VALOR_VACIO);
		valores.put(BROKFEEAMT, this.VALOR_VACIO);
		valores.put(BROK, this.VALOR_VACIO);
		valores.put(YIELD_8, this.VALOR_VACIO);
		valores.put(SPREADRATE_8, this.VALOR_VACIO);
		valores.put(COST, this.VALOR_VACIO);
		valores.put(RATECODE, this.VALOR_VACIO);
		valores.put(DELAYDELVIND, this.VALOR_VACIO);
		valores.put(DEALDATE , this.VALOR_VACIO);
		valores.put(DEALTIME , this.VALOR_VACIO);
		valores.put(DEALTEXT, this.VALOR_VACIO);
		valores.put(EXCHIND, this.VALOR_VACIO);
		valores.put(VERIND, this.VALOR_VACIO);
		valores.put(VERDATE, this.VALOR_VACIO);
		valores.put(STANDINSTR, this.VALOR_VACIO);
		valores.put(REVREASON, this.VALOR_VACIO);
		valores.put(REVTEXT, this.VALOR_VACIO);
		valores.put(CONVINTAMT, this.VALOR_VACIO);
		valores.put(CONVINTBAMT, this.VALOR_VACIO);
		valores.put(SETTAMT, this.VALOR_VACIO);
		valores.put(SETTBASEAMT, this.VALOR_VACIO);
		valores.put(COSTAMT, this.VALOR_VACIO);
		valores.put(COSTBAMT, this.VALOR_VACIO);
		valores.put(WHTAMT, this.VALOR_VACIO);
		valores.put(INTCCY, this.VALOR_VACIO);
		valores.put(SETTCCY, this.VALOR_VACIO);
		valores.put(SETTPROCEXCHRATE_8, this.VALOR_VACIO);
		valores.put(SETTPROCTERMS, this.VALOR_VACIO);
		valores.put(SETTPROCPREMDISC_8, this.VALOR_VACIO);
		valores.put(INTSETTEXCHRATE_8, this.VALOR_VACIO);
		valores.put(INTSETTTERMS, this.VALOR_VACIO);
		valores.put(INTSETTPREMDISC_8, this.VALOR_VACIO);
		valores.put(SETTBASEEXCHRATE_8, this.VALOR_VACIO);
		valores.put(SETTBASETERMS , this.VALOR_VACIO);
		valores.put(SETTBASEPREMDISC_8, this.VALOR_VACIO);
		valores.put(INTBASEEXCHRATE_8, this.VALOR_VACIO);
		valores.put(INTBASETERMS , this.VALOR_VACIO);
		valores.put(INTBASEPREMDISC_8, this.VALOR_VACIO);
		valores.put(CCYSMEANS , this.VALOR_VACIO);
		valores.put(CCYSACCT, this.VALOR_VACIO);
		valores.put(BENBIC, this.VALOR_VACIO);
		valores.put(BEN1, this.VALOR_VACIO);
		valores.put(BEN2, this.VALOR_VACIO);
		valores.put(BEN3, this.VALOR_VACIO);
		valores.put(BEN4, this.VALOR_VACIO);
		valores.put(RECDELBIC , this.VALOR_VACIO);
		valores.put(RECDEL1 , this.VALOR_VACIO);
		valores.put(RECDEL2 , this.VALOR_VACIO);
		valores.put(RECDEL3 , this.VALOR_VACIO);
		valores.put(RECDEL4 , this.VALOR_VACIO);
		valores.put(COLLATERALID , this.VALOR_VACIO);
		valores.put(OVERRIDEWXTAXIND , this.VALOR_VACIO);
		valores.put(LINKFEDEALNO , this.VALOR_VACIO);
		valores.put(LINKFESEQ , this.VALOR_VACIO);
		valores.put(EOPICSIND , this.VALOR_VACIO);
		valores.put(INTERNALYIELD_8, this.VALOR_VACIO);
		valores.put(INTERNALDISCRATE_8, this.VALOR_VACIO);
		valores.put(INTERNALPRICE_8 , this.VALOR_VACIO);
		valores.put(INTERNALPROCEEDAMT, this.VALOR_VACIO);
		valores.put(INTERNALSPREADRATE_8, this.VALOR_VACIO);
		valores.put(MARKUPCOMMAMT , this.VALOR_VACIO);
		valores.put(AMORTYIELD_8 , this.VALOR_VACIO);
		valores.put(AMORTIND , this.VALOR_VACIO);
		valores.put(PLEDGEID , this.VALOR_VACIO);
		valores.put(PRODUCT , this.VALOR_VACIO);
		valores.put(PRODTYPE , this.VALOR_VACIO);
		valores.put(ISSUER , this.VALOR_VACIO);
		valores.put(CRATING , this.VALOR_VACIO);
		valores.put(RATCNO , this.VALOR_VACIO);
		valores.put(FROMDAYS , this.VALOR_VACIO);
		valores.put(TODAYS , this.VALOR_VACIO);
		valores.put(ASSIGNSEQ , this.VALOR_VACIO);
		valores.put(RECOURSEIND , this.VALOR_VACIO);
		valores.put(USUALID , this.VALOR_VACIO);
		valores.put(SUPPCONFIND , this.VALOR_VACIO);
		valores.put(SUPPSEC , this.VALOR_VACIO);
		valores.put(SUPPCCY , this.VALOR_VACIO);
		valores.put(this.TIPO_MENSAJE, this.RENTA_FIJA);
		valores.put(this.ORDENEID, this.VALOR_VACIO);
		valores.put(this.BRANCH, this.BRANCHDEFECTO);

	}
}
