/*
 * JSP generated by Resin-4.0.41 (built Mon, 22 Sep 2014 09:54:25 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.math.BigDecimal;
import javax.naming.InitialContext;
import javax.sql.DataSource;
import java.util.*;
import java.text.*;
import java.util.Date;
import com.bdv.infi.util.Utilitario;
import com.bdv.infi.logic.interfaz_altair.FactoryAltair;
import com.bdv.infi.logic.interfaces.TransaccionFinanciera;
import com.bancovenezuela.comun.data.OrdenOperacion;

public class _procesoaltair__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=ISO-8859-1");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
try {
	String jndiInfi= "java:comp/env/jdbc/infi";
	InitialContext ic = new InitialContext();	
	DataSource dsInfi = (DataSource) ic.lookup(jndiInfi);
	
	FactoryAltair factoryAltair = new FactoryAltair(dsInfi,this.getServletContext());
	
	
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((request.getParameter("idoperacion")==null?"0":request.getParameter("idoperacion")));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((request.getParameter("idorden")==null?"0":request.getParameter("idorden")));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((request.getParameter("codoperacion")==null?"Especificar":request.getParameter("codoperacion")));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((request.getParameter("cuenta")==null?"Especificar":request.getParameter("cuenta")));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((request.getParameter("serial")==null?"Especificar":request.getParameter("serial")));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((request.getParameter("monto")==null?"0":request.getParameter("monto")));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print(("VEF"));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((request.getParameter("centro")==null?"Especificar":request.getParameter("centro")));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((request.getParameter("retencion")==null?"Especificar":request.getParameter("retencion")));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    
	if(!request.getParameter("idoperacion").equals(null) && !request.getParameter("idoperacion").equals("0"))
	{
		OrdenOperacion ordenOperacion = new OrdenOperacion();
		ordenOperacion.setIdOperacion(Long.parseLong(request.getParameter("idoperacion")));
		ordenOperacion.setIdOrden(Long.parseLong(request.getParameter("idorden")));
		ordenOperacion.setCodigoOperacion(request.getParameter("codoperacion"));
		ordenOperacion.setNumeroCuenta(request.getParameter("cuenta"));
		ordenOperacion.setSerialContable(request.getParameter("serial"));
		ordenOperacion.setMontoOperacion(new BigDecimal(request.getParameter("monto")));
		ordenOperacion.setIdMoneda(request.getParameter("moneda"));
		ordenOperacion.setCentroContable(request.getParameter("centro"));
		ordenOperacion.setNumeroRetencion(request.getParameter("retencion"));
		ordenOperacion.setTipoTransaccionFinanc(request.getParameter("transaccion"));
		
		
		ArrayList ordenesOperacionArrayList = new ArrayList();
		ordenesOperacionArrayList.add(ordenOperacion);
		factoryAltair.nombreUsuario=request.getParameter("nm");
		factoryAltair.aplicarOrdenes(ordenesOperacionArrayList);		
		
		//Verifica si es reverso
		if(request.getParameter("rev")!=null){
			
    out.write(_jsp_string11, 0, _jsp_string11.length);
    
			factoryAltair.aplicarReverso(ordenOperacion);
		}
	
	
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((ordenOperacion.getNumeroRetencion()));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((ordenOperacion.getNumeroMovimiento()));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((ordenOperacion.getStatusOperacion()));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    
	}
} catch(Exception e){
	
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((e.getMessage() ));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    
	e.printStackTrace();
}

    out.write(_jsp_string18, 0, _jsp_string18.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -5778918481123896327L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("procesoAltair.jsp"), 5065259924739078496L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string13;
  private final static char []_jsp_string1;
  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string11;
  private final static char []_jsp_string10;
  private final static char []_jsp_string15;
  private final static char []_jsp_string16;
  private final static char []_jsp_string4;
  private final static char []_jsp_string14;
  private final static char []_jsp_string8;
  private final static char []_jsp_string2;
  private final static char []_jsp_string17;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string18;
  private final static char []_jsp_string5;
  private final static char []_jsp_string12;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n\r\n\r\n\r\n\r\n\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n<title>Probando conexiones INFI</title>\r\n</head>\r\n<body>\r\n<form action=\"\">\r\n".toCharArray();
    _jsp_string13 = "</p>\r\n	<p style=\"color:blue;\">N\u00famero Movimiento:".toCharArray();
    _jsp_string1 = "\r\n		<form action=\"procesoAltair.jsp\">\r\n		\r\n		Id Operaci\u00f3n Financiera :<input type=\"text\" name=\"idoperacion\" value=\"".toCharArray();
    _jsp_string7 = "\"><br>\r\n		Moneda : <input type=\"text\" name=\"moneda\" value=\"".toCharArray();
    _jsp_string9 = "\"><br>\r\n		N\u00famero de Retenci\u00f3n : <input type=\"text\" name=\"retencion\" value=\"".toCharArray();
    _jsp_string11 = "\r\n			Aplicando Reverso\r\n			".toCharArray();
    _jsp_string10 = "\"><br>\r\n		<SELECT NAME=\"transaccion\" SIZE=1/>				\r\n					<OPTION VALUE=\"CRE\" SELECTED/>Cr\u00e9dito-2484</OPTION>\r\n					<OPTION VALUE=\"DES\" SELECTED/>Desbloqueo</OPTION>\r\n					<OPTION VALUE=\"BLO\" SELECTED/>Bloqueo-1501</OPTION>\r\n					<OPTION VALUE=\"DEB\" SELECTED/>D\u00e9bito-6975</OPTION>\r\n	 	</SELECT>\r\n	 	<input type=\"checkbox\" value=\"rev\" name=\"rev\">Aplicar Reverso<br>\r\n		<input type=\"submit\" value=\"Probar\">\r\n</form>\r\n	".toCharArray();
    _jsp_string15 = "</p>		\r\n	".toCharArray();
    _jsp_string16 = "\r\n	<p style=\"color:FF0000;\">Error ".toCharArray();
    _jsp_string4 = "\"><br>\r\n		N\u00famero de Cuenta : <input type=\"text\" name=\"cuenta\" value=\"".toCharArray();
    _jsp_string14 = "</p>	\r\n	<p style=\"color:blue;\">Status de la Operaci\u00f3n:".toCharArray();
    _jsp_string8 = "\" readonly=\"readonly\"><br>\r\n		Centro Contable :  <input type=\"text\" name=\"centro\" value=\"".toCharArray();
    _jsp_string2 = "\"><br>\r\n		Id Orden : <input type=\"text\" name=\"idorden\" value=\"".toCharArray();
    _jsp_string17 = "</p>	\r\n	".toCharArray();
    _jsp_string6 = "\"><br>\r\n		Monto Operaci\u00f3n (separador decimal el punto):  <input type=\"text\" name=\"monto\" value=\"".toCharArray();
    _jsp_string3 = "\"><br>\r\n		C\u00f3digo Operaci\u00f3n : <input type=\"text\" name=\"codoperacion\" value=\"".toCharArray();
    _jsp_string18 = "\r\n<input type=\"text\" name=\"nm\" value=\"NM13749\">\r\n\r\n</form>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string5 = "\"><br>\r\n		Serial Contable : <input type=\"text\" name=\"serial\" value=\"".toCharArray();
    _jsp_string12 = "\r\n	<p style=\"color:blue;\">N\u00famero Retenci\u00f3n:".toCharArray();
  }
}
