SELECT A.PARGRP_NOMBRE AS NOMBRE, B.PARTIP_NOMBRE_PARAMETRO AS PARAMETRO, C.PARVAL_VALOR AS VALOR, C.UPD_FECHA AS FECHA_ACT 
FROM INFI_TB_001_PARAM_GRUPO A, INFI_TB_002_PARAM_TIPOS B, INFI_TB_004_PARAM_VALORES C
WHERE A.PARGRP_ID = B.PARGRP_ID
  AND B.PARTIP_NOMBRE_PARAMETRO = C.PARTIP_NOMBRE_PARAMETRO