SELECT D.*
FROM INFI_TB_Z11_PROCESOS C, INFI_TB_Z12_REGISTROS D
WHERE C.Z11_COD_PROCESO = D.Z11_COD_PROCESO
AND C.Z10_CO_CODIGO_ARCHIVO = @cod_archivo@
AND C.Z11_COD_PROCESO = @cod_proceso@
AND D.Z12_ESTATUS = 1
