//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : INFI-SITME
//  @ File Name : MensajeCanal.java
//  @ Date : 08/02/2011
//  @ Author : 
//
//



package com.bdv.infi.logic.interfaz_varias;


public class MensajeCanal {
	public String codigoCanal;
	public String codigoMensaje;
	public String mensaje;
	public String descripcion;
}
