SELECT count(A.PARGRP_NOMBRE) AS CONTEO
FROM INFI_TB_001_PARAM_GRUPO A, INFI_TB_002_PARAM_TIPOS B, INFI_TB_004_PARAM_VALORES C
WHERE A.PARGRP_ID = B.PARGRP_ID
  AND B.PARTIP_NOMBRE_PARAMETRO = C.PARTIP_NOMBRE_PARAMETRO